name = "xml2map"
version = "0.0.1"

description = "Converts XML to json-like map for decode compatibility"
licences = ["Apache-2.0"]
repository = { type = "github", user = "floatdrop", repo = "gleam_xml2map" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
